import { Injectable } from '@angular/core';
import { Lagertechnik } from './model/Lagertechnik.interface';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  alternatives: { name: string; lagertechnik: Lagertechnik }[] = [
    {
      name: 'fachbodenRegalPicklist',
      lagertechnik: {
        name: 'Fachbodenregal mit Picklist',
        kommisionierStrategie: 'Picklist',
        lagerart: 'Klt',
        automatisierung: false,
        eignungKommissionierung: true,
        fifo: true,
        direktzugriff: true,
        schutz: false,

        maxGewicht: 50,
        maxHöhe: 3,
        kühllagerEignung: 2,

        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 2,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,

        investitionskosten: 1,
        kommissionierLeistung: 1,
        personalbedarf: 3,
        raumnutzungsgrad: 1,
        innovationsgrad: 1,
        ausfallsicherheit: 4,
        leistungsflexibilität: 2,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 3,
        skalierbarkeitKapazität: 3,
        ergonomie: 1,
        fehlerquote: 4,
      },
    },
    {
      name: 'fachbodenRegalMDE',
      lagertechnik: {
        name: 'Fachbodenregal mit Mobilen Datenendgeräte',
        lagerart: 'Klt',
        kommisionierStrategie: 'MDE',
        automatisierung: false,
        investitionskosten: 1,
        eignungKommissionierung: true,
        kommissionierLeistung: 2,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 2,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 1,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'fachbodenRegalPbV',
      lagertechnik: {
        name: 'Fachbodenregal mit Pick by Voice',
        lagerart: 'Klt',
        kommisionierStrategie: 'Pick by Voice',
        automatisierung: false,
        investitionskosten: 2,
        eignungKommissionierung: true,
        kommissionierLeistung: 2,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 2,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 1,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'fachbodenRegalPbL',
      lagertechnik: {
        name: 'Fachbodenregal mit Pick by Light',
        lagerart: 'Klt',
        kommisionierStrategie: 'Pick by Light',
        automatisierung: false,
        investitionskosten: 2,
        eignungKommissionierung: true,
        kommissionierLeistung: 3,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 1,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 1,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'fachbodenRegalMehrgeschossig',
      lagertechnik: {
        name: 'Mehrgeschossiges Fachbodenregal',
        lagerart: 'Klt',
        automatisierung: false,
        investitionskosten: 2,
        eignungKommissionierung: true,
        kommissionierLeistung: 1,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 2,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,
        maxHöhe: 20,
        raumnutzungsgrad: 2,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'durchLaufregalPickList',
      lagertechnik: {
        name: 'Durchlaufregal Picklist',
        lagerart: 'Klt',
        kommisionierStrategie: 'Picklist',
        automatisierung: false,
        investitionskosten: 1,
        eignungKommissionierung: true,
        kommissionierLeistung: 2,
        fifo: true,
        direktzugriff: false,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 3,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 1,
        mittelArtikelanzahl: 2,
        geringArtikelanzahl: 3,
        hochbestandsmenge: 3,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 1,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 4,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'durchLaufregalMDE',
      lagertechnik: {
        name: 'Durchlaufregal MDE',
        lagerart: 'Klt',
        kommisionierStrategie: 'MDE',
        automatisierung: false,
        investitionskosten: 1,
        eignungKommissionierung: true,
        kommissionierLeistung: 3,
        fifo: true,
        direktzugriff: false,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 2,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 1,
        mittelArtikelanzahl: 2,
        geringArtikelanzahl: 3,
        hochbestandsmenge: 3,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 1,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'durchLaufregalPbL',
      lagertechnik: {
        name: 'Durchlaufregal Pick by Light',
        lagerart: 'Klt',
        kommisionierStrategie: 'Pick by Light',
        automatisierung: false,
        investitionskosten: 2,
        eignungKommissionierung: true,
        kommissionierLeistung: 4,
        fifo: true,
        direktzugriff: false,
        personalbedarf: 3,
        ergonomie: 1,
        fehlerquote: 1,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 1,
        mittelArtikelanzahl: 2,
        geringArtikelanzahl: 3,
        hochbestandsmenge: 3,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 1,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'fachbodenRegalVertikal',
      lagertechnik: {
        name: 'Fachbodenregal mit Vertikal-Kommissionierer',
        automatisierung: false,
        investitionskosten: 2,
        eignungKommissionierung: true,
        kommissionierLeistung: 1,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 3,
        ergonomie: 2,
        fehlerquote: 2,
        schutz: false,
        kühllagerEignung: 2,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 1,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 2,
        geringBestandsmenge: 3,
        maxHöhe: 20,
        raumnutzungsgrad: 2,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitKapazität: 2,
        skalierbarkeitLeistung: 2,
        lagerart: 'Klt',
      },
    },
    {
      name: 'verschiebeRegal',
      lagertechnik: {
        name: 'Verschieberegal',
        lagerart: 'Klt',
        automatisierung: false,
        eignungKommissionierung: false,
        fifo: false,
        direktzugriff: false,
        schutz: false,
        maxGewicht: 50,
        maxHöhe: 3,
        kühllagerEignung: 0,
        investitionskosten: 3,
        kommissionierLeistung: 3,
        ergonomie: 3,
        fehlerquote: 3,
        personalbedarf: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 3,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 3,
        skalierbarkeitLeistung: 3,
        skalierbarkeitKapazität: 3,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 3,
        hochbestandsmenge: 3,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
      },
    },
    {
      name: 'akl',
      lagertechnik: {
        name: 'AKL',
        lagerart: 'Klt',
        automatisierung: true,
        eignungKommissionierung: true,
        fifo: true,
        direktzugriff: false,
        schutz: false,
        maxGewicht: 50,
        maxHöhe: 3,
        kühllagerEignung: 0,
        investitionskosten: 4,
        kommissionierLeistung: 3,
        ergonomie: 3,
        fehlerquote: 2,
        personalbedarf: 2,
        raumnutzungsgrad: 3,
        innovationsgrad: 3,
        ausfallsicherheit: 2,
        leistungsflexibilität: 1,
        umbauflexibilität: 3,
        skalierbarkeitLeistung: 3,
        skalierbarkeitKapazität: 3,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 3,
        hochbestandsmenge: 3,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
      },
    },
    {
      name: 'vertikalLift',
      lagertechnik: {
        name: 'Vertikallift',
        lagerart: 'Klt',

        automatisierung: true,
        investitionskosten: 3,
        eignungKommissionierung: true,
        kommissionierLeistung: 2,
        fifo: true,
        direktzugriff: false,
        personalbedarf: 2,
        ergonomie: 3,
        fehlerquote: 2,
        schutz: true,
        kühllagerEignung: 1,
        maxGewicht: 30,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 2,
        leistungsflexibilität: 1,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'paternosterrgal',
      lagertechnik: {
        name: 'Paternosterregal',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 3,
        eignungKommissionierung: true,
        kommissionierLeistung: 1,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 3,
        fehlerquote: 2,
        schutz: true,
        kühllagerEignung: 1,
        maxGewicht: 30,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 2,
        leistungsflexibilität: 1,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'horizontalkarussel',
      lagertechnik: {
        name: 'Horizontalkarussel',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 3,
        eignungKommissionierung: true,
        kommissionierLeistung: 2,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 3,
        fehlerquote: 2,
        schutz: true,
        kühllagerEignung: 1,
        maxGewicht: 50,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 2,
        leistungsflexibilität: 1,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'regalgebundeneShuttleKlassisch',
      lagertechnik: {
        name: 'Regalgebundene Shuttle',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 4,
        eignungKommissionierung: true,
        kommissionierLeistung: 4,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 4,
        fehlerquote: 1,
        schutz: true,
        kühllagerEignung: 2,
        maxGewicht: 150,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 3,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'verfahrbareRegale',
      lagertechnik: {
        name: 'Verfahrbare Regale',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 3,
        eignungKommissionierung: true,
        kommissionierLeistung: 3,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 2,
        fehlerquote: 2,
        schutz: true,
        kühllagerEignung: 1,
        maxGewicht: 30,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 2,
        innovationsgrad: 1,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'blocklager',
      lagertechnik: {
        name: 'Blocklager (Autostore etc.)',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 4,
        eignungKommissionierung: true,
        kommissionierLeistung: 4,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 4,
        fehlerquote: 1,
        schutz: true,
        kühllagerEignung: 0,
        maxGewicht: 30,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 2,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 4,
        innovationsgrad: 2,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
    {
      name: 'regalgebundeneShuttleSykpod',
      lagertechnik: {
        name: 'Regalungebundene Shuttle (Skypod, Geek+, …)',
        lagerart: 'Klt',
        automatisierung: true,
        investitionskosten: 4,
        eignungKommissionierung: true,
        kommissionierLeistung: 3,
        fifo: true,
        direktzugriff: true,
        personalbedarf: 2,
        ergonomie: 3,
        fehlerquote: 1,
        schutz: true,
        kühllagerEignung: 0,
        maxGewicht: 30,
        hochArtikelanzahl: 3,
        mittelArtikelanzahl: 3,
        geringArtikelanzahl: 2,
        hochbestandsmenge: 1,
        mittelBestandsmenge: 3,
        geringBestandsmenge: 3,
        maxHöhe: 3,
        raumnutzungsgrad: 2,
        innovationsgrad: 3,
        ausfallsicherheit: 3,
        leistungsflexibilität: 3,
        umbauflexibilität: 2,
        skalierbarkeitLeistung: 2,
        skalierbarkeitKapazität: 2,
      },
    },
  ];

  eabCriteria: string[] = [
    'lagerart',
    'kommisionierStrategie',
    'automatisierung',
    'eignungKommissionierung',
    'fifo',
    'direktzugriff',
    'schutz',
    'maxGewicht',
    'maxHöhe',
    'kühllagerEignung',
    'hochArtikelanzahl',
    'mittelArtikelanzahl',
    'geringArtikelanzahl',
    'hochbestandsmenge',
    'mittelBestandsmenge',
    'geringBestandsmenge',
  ];
  //negativ gibt an ob großer => besser oder größér => schlechter
  perfCriteria: { name: string; negative: boolean }[] = [
    { name: 'kommissionierLeistung', negative: false },
    { name: 'ergonomie', negative: false },
    { name: 'raumnutzungsgrad', negative: false },
    { name: 'innovationsgrad', negative: false },
    { name: 'ausfallsicherheit', negative: false },
    { name: 'leistungsflexibilität', negative: false },
    { name: 'umbauflexibilität', negative: false },
    { name: 'skalierbarkeitLeistung', negative: false },
    { name: 'skalierbarkeitKapazität', negative: false },

    { name: 'investitionskosten', negative: true },
    { name: 'fehlerquote', negative: true },
    { name: 'personalbedarf', negative: true },
  ];
  perfCriteriaWithoutKommissionierung: { name: string; negative: boolean }[] = [
    { name: 'raumnutzungsgrad', negative: false },
    { name: 'innovationsgrad', negative: false },
    { name: 'ausfallsicherheit', negative: false },
    { name: 'leistungsflexibilität', negative: false },
    { name: 'umbauflexibilität', negative: false },
    { name: 'skalierbarkeitLeistung', negative: false },
    { name: 'skalierbarkeitKapazität', negative: false },

    { name: 'investitionskosten', negative: true },
  ];

  rankingMap: Map<string, number> = new Map();
  kommissionierung: boolean = true;
  currentAlternatives: Lagertechnik[] = [];
  constructor() {}
}
